import React from 'react';
import Swal from 'sweetalert2';

function Details(name) {

    console.log(name)
    const detailedInfo = {
        'Sun': "The Sun is the heart of our solar system and the source of all life and energy here on Earth. It accounts for more than 99.85% of the mass of the entire solar system and is approximately 4.6 billion years old. The Sun's atmosphere is composed of several layers, mainly the photosphere, the chromosphere, and the corona. The outermost layer, the corona, extends millions of kilometers into space and is visible during a total solar eclipse. The Sun's immense energy, which is the main driver of weather and climate on Earth, comes from nuclear fusion processes in its core where hydrogen atoms are combined to form helium, releasing light and heat.",
        'Mercury': 'Mercury, named after the Roman deity who served as a messenger to the gods, is notable for its rapid transit across the sky and its extreme temperatures. Despite being visible from Earth, little was known about it until the space age. Mercury has no atmosphere to speak of, which means there are no weather patterns and the sky is always black, exposing the surface to extreme temperatures. Its surface is heavily cratered and similar in appearance to the Moon, showing extensive mare-like plains and heavy impacts from collisions with comets and asteroids.',
        'Venus': "Venus, the second planet from the Sun, is named after the Roman goddess of love and beauty. It is the closest planetary neighbor to Earth and is similar in structure but slightly smaller in size. Venus is shrouded by an opaque layer of highly reflective clouds of sulfuric acid, preventing its surface from being seen from space in visible light. It has the densest atmosphere of the four terrestrial planets, consisting mostly of carbon dioxide, with a surface pressure 92 times that of Earth. This leads to Venus' surface temperature being the hottest in the solar system, averaging around 467°C.",
        'Earth': "Earth is the third planet from the Sun and the only known object in the universe known to harbor life. Its vast oceans and atmospheric conditions support a wide variety of life forms. The planet's dynamic surface has been shaped over billions of years by tectonic processes, erosion, and weather patterns. Earth's atmosphere is radically different from those of other planets, being composed largely of nitrogen and oxygen, and plays a crucial role in Earth's water cycle and climate regulation. The presence of life has significantly altered the atmospheric composition and other planetary characteristics.",
        'Mars': 'Mars is known as the "Red Planet" due to its reddish appearance, caused by iron oxide prevalent on its surface. Mars is a terrestrial planet with a thin atmosphere, featuring surface conditions both reminiscent of both the impact craters of the Moon and the valleys, deserts, and polar ice caps of Earth. Signs of ancient floods but no liquid water currently exist on the surface. Mars has two small moons, Phobos and Deimos, thought to be captured asteroids. It is the target of multiple ongoing and future space missions, aimed at exploring its surface and potential to host life.',
        'Jupiter': "Jupiter is the largest planet in our solar system and is known for its many moons, including the four large Galilean moons: Io, Europa, Ganymede, and Callisto. Ganymede is the largest moon in the solar system, larger even than the planet Mercury. Jupiter is famous for its Great Red Spot, a giant storm larger than Earth that has been raging for hundreds of years. The planet's atmosphere is made up mostly of hydrogen and helium, and it does not have a well-defined solid surface. Jupiter's magnetic field is fourteen times stronger than Earth's, leading to spectacular auroras at its poles.",
        'Saturn': "Saturn is most well-known for its stunning ring system, composed mainly of ice particles, rocky debris, and dust. Its atmosphere, like Jupiter's, is primarily hydrogen and helium but contains traces of other substances like methane and water ice. Saturn has over 80 moons, with Titan being the largest — a moon larger than the planet Mercury and the only moon in the solar system with a substantial atmosphere. The planet is also known for its hexagon-shaped storm at the north pole.",
        'Uranus': 'Uranus is unique among the planets in our solar system for its tilted axis, which causes it to rotate on its side. This unique tilt results in extreme variations in its seasons, with each pole getting around 42 years of continuous sunlight followed by 42 years of darkness. Uranus is an ice giant with a blue-green color due to methane in its atmosphere. The planet has a ring system and 27 known moons, named after characters from the works of William Shakespeare and Alexander Pope.',
        'Neptune': "Neptune is the eighth and farthest known planet from the Sun in our solar system. Named after the Roman god of the sea, it is the fourth-largest planet by diameter and the third-largest by mass. Despite its size, Neptune was not visible to the ancient civilizations because of its extreme distance from Earth. The planet is not visible to the naked eye and was first observed in 1846 through mathematical predictions rather than through regular telescopic viewing. Neptune's atmosphere is made primarily of hydrogen and helium, with traces of methane, water, and ammonia, which gives the planet its characteristic blue color. This ice giant has a turbulent atmosphere with the fastest winds in the solar system, reaching speeds of more than 2,000 kilometers per hour. The Great Dark Spot, a storm comparable to Jupiter's Great Red Spot, is one of its most notable weather patterns, although it appears to come and go unpredictably. Neptune has a complex ring system, which is made up of several rings and “ring arcs,” segments of rings that have clumped together. Neptune's magnetic field is about 27 times more powerful than Earth's. The planet has 14 known moons, with Triton being the largest. Triton is geologically active, with geysers thought to spew liquid nitrogen and is the only large moon in the solar system to orbit in the opposite direction of its planet's rotation, which suggests that Triton was captured by Neptune's gravity rather than having formed in place."
    };

    Swal.fire({
        title: name,
        html: `
            <div>
                <p>${detailedInfo[name]}</p>
            </div>
        `,
        showCloseButton: true,
        width: 'auto',
    });
}

export default Details;